---
# playbook.yml
- name: 'Configure VM'
  hosts: all
  become: true
  tasks:
    - name: Update package
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes
    - name: Install default packages
      import_tasks: "../../../az-pipeline-template-tf-ansible/ansible/defaultpackages/playbook.yml"
    - name: Install NGINX
      ansible.builtin.apt:
        package:
          - nginx
        state: latest
        update_cache: true
    - name: Enable service nginx, and start it
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
    - name: Deploy the custom web page
      ansible.builtin.copy:
        src: ./files/index.html
        dest: /var/www/html/index.nginx-debian.html